# Generated by Django 5.0.2 on 2024-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_secretgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
