# Generated by Django 5.0.2 on 2024-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_description_text_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description_text',
            field=models.TextField(blank=True),
        ),
    ]
