# Generated by Django 5.0.2 on 2024-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
